### ISSUE TITLE
Issues with brackets

### ISSUE THREAD

**Issue by technion** [defaultnamehere/verylegit.link#1]
Hi,

A+ tool, will use again.

I just wanted to report a difficulty with some links. For example, I created:

http://click.here.to.get.ripped.in.three.weeks.verylegit.link/0x8c*paypal)985iphone(botnet$torrent.jar.dmg.docm

Which is a link to:

pusheen.com

However, if I send this link to someone on Facebook, Facebook's URL parser assumes that the URL stops at the bracket, and sends my friend a broken link. You can see a similar issue if I try to use Markdown and share this link here:

[Click Here](http://click.here.to.get.ripped.in.three.weeks.verylegit.link/0x8c*paypal)985iphone(botnet$torrent.jar.dmg.docm)

Could I recommend pulling brackets from the output?

**Comment by defaultnamehere** [comment]
Good point! Just fixed this by removing "<>()".
