### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by mtricht** [defaultnamehere/verylegit.link#5]

**Comment by imerkle** [comment]
coz fun

**Comment by jaredchu** [comment]
It make the link longer instead of shorter

**Comment by viAtom** [comment]
Seems like you don't get the joke, but I agree on the "shortener" part that you should modify or remove, because it actually makes it longer ("URL Longener" !)

**Comment by dermorz** [comment]
Oh, when seeing this issue title, I thought the question was:
**Why did you create a new project with python2?**

**Comment by filipekiss** [comment]
> Science is not about "why?". It is about "why not?".

*JOHNSON, Cave - Circa 1972*

**Comment by ghost** [comment]
This tool adds the extra layer of authority to my marketing emails I've been looking for, the developers of this project are surely saints.
